version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development # Change to production as needed
    environment:
      - FLASK_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: development # Change to production as needed
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
